### PR TITLE
Fix NULL allocator and racy condition.

### LINKED ISSUE #1187: does rcl_subscription_get_default_options has data race?
## Bug report

please note this is only guess.

during checking source code of rcl, I found
[```](https://github.com/ros2/rcl/blob/bfe00f71b7056bb64b27a8d5f5bacefe0564c43e/rcl/src/rcl/subscription.c#L230)
```
 static rcl_subscription_options_t default_options;
  // Must set these after declaration because they are not a compile time constants.
  default_options.qos = rmw_qos_profile_default;
  default_options.allocator = rcl_get_default_allocator();
  default_options.rmw_subscription_options = rmw_get_default_subscription_options();
```

while being called from multi thread, is this data race? recently some data race being found for similar code pattern, please see
https://github.com/ros2/rmw/issues/377
https://github.com/ros2/rcutils/issues/477

and a (maybe) error log  for this
```
 'invalid allocator, at external/ros2_rcl/rcl/src/rcl/subscription.c:219'
rcutils_reset_error() should be called after error handling to avoid this.
invalid allocator, at external/ros2_rcl/rcl/src/rcl/subscription.c:219
terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
what():  could not create subscription: invalid allocator, at external/ros2_rcl/rcl/src/rcl/subscription.c:219
```

- Operating System:
  - ubuntu 22.04
- Installation type:
  - build from source
- Version or commit hash:
  - 5.3.7
- DDS implementation:
  - not sure
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue
this is only guess

#### Additional information

----

### PR DESCRIPTION
**Pull request by fujitatomoya**
closes https://github.com/ros2/rcl/issues/1187

### CODE REVIEW

File: rcl/src/rcl/context.c [hunk 1]
```diff
@@ -28,7 +28,7 @@ extern "C"
 rcl_context_t
 rcl_get_zero_initialized_context(void)
 {
-  static rcl_context_t context = {
+  rcl_context_t context = {
```
Comment (fujitatomoya) [inline rcl/src/rcl/context.c:31]: use stack memory instead, so that we can avoid the racy condition with multi-threaded manner.

File: rcl/src/rcl/subscription.c [hunk 2]
```diff
@@ -227,7 +228,7 @@ rcl_subscription_options_t
 rcl_subscription_get_default_options(void)
 {
   // !!! MAKE SURE THAT CHANGES TO THESE DEFAULTS ARE REFLECTED IN THE HEADER DOC STRING
-  static rcl_subscription_options_t default_options;
+  rcl_subscription_options_t default_options;
```
Comment (comicfans) [inline rcl/src/rcl/subscription.c:231]: Looks good to me, should resolve the data race

**Review by comicfans — APPROVED** [review]

**Review by clalancette — APPROVED** [review]
Looks good to me with green CI.

**Comment by clalancette** [comment]
Pulls: https://github.com/ros2/rcl/pull/1188
Gist: https://gist.githubusercontent.com/clalancette/f418b9082406471f8d78135265878dfb/raw/b63bc094762989901b2a078dd32377e7ac8f2dbf/ros2.repos
BUILD args:  --packages-above-and-dependencies rcl
TEST args:  --packages-above rcl
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14588
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21867/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16137/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1374/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22579/)
