### PR TITLE
Ensure that context instance id storage is aligned correctly

### LINKED ISSUE #363: bus error on armv7l
## Bug report

Hi, I have compiled natively ros2 crystal on a raspberry pi 3b and seems that there is a bug somewhere, when I try to launch a demo talker I get a bus error, seems something related with some `Alignment trap`. I open this issue in `rcl` repo because the exception is raised when `rcl_get_zero_initialized_context` is called.

**Required Info:**

- Operating System:
  - 2018-11-13-raspbian-stretch-full
- Installation type:
  - from sources, native build
- Version or commit hash:
  - 657d9e84c73e4268176efd163e96fda73c1a76d9
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - rcl

#### Steps to reproduce issue

```
colcon build --symlink-install --packages-ignore qt_gui_cpp rqt_gui_cpp --packages-up-to demo_nodes_cpp --executor sequential --cmake-args " -DBUILD_TESTING=OFF" --event-handlers console_direct+
# source ros2 install
./build/demo_nodes_cpp/talker
```

#### Expected behavior
demo_nodes_cpp talker should be launch

#### Actual behavior
An exception is raised: "Bus error"
gdb output:
```
gdb ./build/demo_nodes_cpp/talker
r
Program received signal SIGBUS, Bus error.
0x76edb80c in rcl_get_zero_initialized_context () from /home/pi/ros2_ws/install/rcl/lib/librcl.so
```
journalctl will output the next:
```
dic 19 17:57:53 raspberrypi kernel: Alignment trap: not handling instruction e1b20f9f at [<ffff0f70>]
dic 19 17:57:53 raspberrypi kernel: Unhandled fault: alignment exception (0x001) at 0x7691f83c
dic 19 17:57:53 raspberrypi kernel: pgd = b9314000
```

### PR DESCRIPTION
**Pull request by sgvandijk**
On 32 bit ARMv7l, casting of the context instance id to an `atomic_uint_least64_t` and initialising it results in SIGBUS if it is not 8 byte aligned. This change fixes that by ensuring that `instance_id_storage` is aligned as `uint_least64_t`.

Closes #363

### CODE REVIEW

**Comment by clalancette** [comment]
The fix seems reasonable to me.  Here's CI (to ensure there are no deleterious effects on other platforms):

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5935/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2461/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4905/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5824/)

**Comment by sgvandijk** [comment]
Just saw yeah, guess one part of C11 not supported.. I am trying a cross platform solution now.

**Comment by sgvandijk** [comment]
I do not have access to Windows, but I have tested the macro with https://godbolt.org/ on GCC, Clang, and MSVC.

It feels less nice to give the explicit amount of bytes to align by, but unfortunately AFAICT `alignas/of` is only supported by MSVC for C++ and I couldn't find another alternative, and it should not be detrimental.

File: rcl/include/rcl/context.h [hunk 1]
```diff
@@ -132,7 +139,7 @@ typedef struct rcl_context_t
    * See this paper for an effort to make this possible in the future:
    *   http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0943r1.html
    */
-  uint8_t instance_id_storage[RCL_CONTEXT_ATOMIC_INSTANCE_ID_STORAGE_SIZE];
+  ALIGNAS_(8) uint8_t instance_id_storage[RCL_CONTEXT_ATOMIC_INSTANCE_ID_STORAGE_SIZE];
```
Comment (sloretz) [inline rcl/include/rcl/context.h]: Does `RCL_CONTEXT_ATOMIC_INSTANCE_ID_STORAGE_SIZE` instead of `8` work?

Comment (sgvandijk) [reply rcl/include/rcl/context.h]: Unfortunately not, this will result in `__declspec(align(sizeof(uint_least64_t)))` and MSVC doesn't like that, giving `syntax error: 'sizeof'`: https://godbolt.org/z/vskBhM

**Comment by jacobperron** [comment]
Ignore the cppcheck failures, it is an unrelated issue ament/ament_lint#116

**Comment by sloretz** [comment]
CI (testing only rcl)
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5960/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2483/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4926/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5849/)

**Comment by sloretz** [comment]
CI looks good, thanks for the PR!
