### PR TITLE
Move the guard condition cleanup after removing callback.

### LINKED ISSUE #876: Failed to get trigger guard condition in jump callback
## Bug report

**Required Info:**

- Operating System:
  - 
Ubuntu 18.04.5 LTS
- Installation type:
binaries 
- Version or commit hash:
  ROS2 FOXY Development
- DDS implementation:
Cyclone DDS Version 0.7.0 https://github.com/ros2/rmw_cyclonedds
- RMW
ROS 2 RMW for Eclipse Cyclone DDS Version 2.2.0 https://github.com/ros2/rmw
 
- Client library (if applicable):
  - 

#### Steps to reproduce issue
The issue is intermittent 

#### Expected behavior
It should run without error 

#### Actual behavior
[planner_server-21] [ERROR 1605305996.010625274] [rcl]: Failed to get trigger guard condition in jump callback (/ros2_foxy_build/core/src/ros2/rcl/rcl/src/rcl/timer.c:114)
[planner_server-21]
[planner_server-21] >>> [rcutils|error_handling.c:108] rcutils_set_error_state()
[planner_server-21] This error state is being overwritten:
[planner_server-21]
[planner_server-21]   'guard_condition_handle not from this implementation, at /ros2_foxy_build/core/src/ros2/rmw_cyclonedds/rmw_cyclonedds_cpp/src/rmw_node.cpp:2713, at /ros2_foxy_build/core/src/ros2/rcl/rcl/src/rcl/guard_condition.c:160'
[planner_server-21]
[planner_server-21] with this new error message:
[planner_server-21]
[planner_server-21]   'guard condition implementation is invalid, at /ros2_foxy_build/core/src/ros2/rcl/rcl/src/rcl/guard_condition.c:174'
[planner_server-21]
[planner_server-21] rcutils_reset_error() should be called after error handling to avoid this.
[planner_server-21] <<<
[planner_server-21] [ERROR 1605306298.359010300] [rcl]: Failed to get trigger guard condition in jump callback (/ros2_foxy_build/core/src/ros2/rcl/rcl/src/rcl/timer.c:114)
[ERROR] [planner_server-21]: process has died [pid 12676, exit code -11, cmd '/opt/ros/foxy/nav2_planner/lib/nav2_planner/planner_server --ros-args -r __node:=planner_server --params-file /tmp/tmpp28qz1d4 -r /tf:=tf -r /tf_static:=tf_static'].

#### Additional information
ROS2 Costmap Planner application

### PR DESCRIPTION
**Pull request by clalancette**
Otherwise, the callback could attempt to take a reference
to a guard condition that has already been deleted.

Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

This should fix #876 , but this is still a draft since I'm doing additional testing on it.

### CODE REVIEW

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13280/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8212/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11015/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13317/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13318/)

**Review by fujitatomoya — APPROVED** [review]
lgtm

**Comment by clalancette** [comment]
All right, the failing tests on Windows are well-known in the nightlies.  So this looks to be working.  Converting this to a real PR now.

**Review by ivanpauno — APPROVED** [review]

File: rcl/src/rcl/timer.c [hunk 1]
```diff
@@ -209,16 +209,19 @@ rcl_timer_fini(rcl_timer_t * timer)
...
+    // The jump callbacks use the guard condition, so we have to remove it
+    // before freeing the guard condition below.
     fail_ret = rcl_clock_remove_jump_callback(timer->impl->clock, _rcl_timer_time_jump, timer);
     if (RCL_RET_OK != fail_ret) {
       RCUTILS_LOG_ERROR_NAMED(ROS_PACKAGE_NAME, "Failed to remove timer jump callback");
     }
   }
+  fail_ret = rcl_guard_condition_fini(&(timer->impl->guard_condition));
+  if (RCL_RET_OK != fail_ret) {
+    RCL_SET_ERROR_MSG("Failure to fini guard condition");
```
Comment (ivanpauno) [inline rcl/src/rcl/timer.c:223]:
```suggestion
    RCL_SET_ERROR_MSG("failed to fini guard condition");
```

this sounds better to me, but I don't mind strongly (and the message was already this).

Comment (clalancette) [reply rcl/src/rcl/timer.c:223]: Yeah, since the message was already this, I'm going to leave it as-is and go ahead and merge it.  Thanks for the review!
