### PR TITLE
fix flaky test

### LINKED ISSUE #1062: Test `test_graph__rmw_connextdds` failing on nightly_win_rep
CI:
 * https://ci.ros2.org/view/nightly/job/nightly_win_rep/2955/testReport/projectroot/test/test_graph__rmw_connextdds/
* https://ci.ros2.org/view/nightly/job/nightly_win_rep/2955/testReport/(root)/projectroot/test_graph__rmw_connextdds/

### PR DESCRIPTION
**Pull request by iuhilnehc-ynos**
to fix https://github.com/ros2/rcl/issues/1062

https://github.com/ros2/rcl/blob/959ef2836e8cb88bcc1805752ad857127684ac4d/rcl/test/rcl/test_graph.cpp#L870
is only called in [VerifySubsystemCount](https://github.com/ros2/rcl/blob/959ef2836e8cb88bcc1805752ad857127684ac4d/rcl/test/rcl/test_graph.cpp#L1025), which expect to cost (20*400ms) if failure happened in the test, 
but we can find `[  FAILED  ] NodeGraphMultiNodeFixture.test_node_info_publishers (3909 ms)` just consume 4s running the test.

I think this [ASSERT](https://github.com/ros2/rcl/blob/959ef2836e8cb88bcc1805752ad857127684ac4d/rcl/test/rcl/test_graph.cpp#L882) can be removed as the discovery in operations ([1](https://github.com/ros2/rcl/blob/959ef2836e8cb88bcc1805752ad857127684ac4d/rcl/test/rcl/test_graph.cpp#L949), [2](https://github.com/ros2/rcl/blob/959ef2836e8cb88bcc1805752ad857127684ac4d/rcl/test/rcl/test_graph.cpp#L957), [3](https://github.com/ros2/rcl/blob/959ef2836e8cb88bcc1805752ad857127684ac4d/rcl/test/rcl/test_graph.cpp#L965), [4](https://github.com/ros2/rcl/blob/959ef2836e8cb88bcc1805752ad857127684ac4d/rcl/test/rcl/test_graph.cpp#L972)) might be asynchronous(doc needs to be updated) which is similar to [rmw_get_publishers_info_by_topic](https://github.com/ros2/rmw/blob/bb044d59df89fac9fed8706aa58a8d7092fa31a2/rmw/include/rmw/get_topic_endpoint_info.h#L34).

`rcl_get_publisher_names_and_types_by_node` -> `rmw_get_publisher_names_and_types_by_node` -> `rmw_api_connextdds_get_publisher_names_and_types_by_node` -> ... -> `get_writer_names_and_types_by_node` -> `GraphCache::get_writer_names_and_types_by_node` ->
	https://github.com/ros2/rmw_dds_common/blob/0dc8af3cc1c471c60a96e896ab66633d486feb50/rmw_dds_common/src/graph_cache.cpp#L891-L898

### CODE REVIEW

**Comment by iuhilnehc-ynos** [comment]
CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18575/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13119/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19313/)

File: rcl/test/rcl/test_graph.cpp [hunk 1]
```diff
@@ -879,7 +879,6 @@ void expect_topics_types(
   rcl_names_and_types_t nat{};
   nat = rcl_get_zero_initialized_names_and_types();
   ret = func(node, topic_name, &nat);
-  ASSERT_EQ(RCL_RET_OK, ret) << rcl_get_error_string().str;
```
Comment (fujitatomoya) [inline rcl/test/rcl/test_graph.cpp:882]: i think keeping this assertion makes sense to check if any error happens. probably what we really want to do here is avoiding `RMW_RET_NODE_NAME_NON_EXISTENT` case only? that said, if `RMW_RET_NODE_NAME_NON_EXISTENT` returns, it will return immediately to next attempt. and if the error is anything else, assert here to stop the test?

Comment (iuhilnehc-ynos) [reply rcl/test/rcl/test_graph.cpp:882]: To return immediately will change the behavior of the `expect` and the debug log. I'll revert to https://github.com/ros2/rcl/pull/1063/commits/d0d9ba336ef8be6d64632af9d93b95c855cce62c.

**Review by clalancette — APPROVED** [review]
Looks good to me with green CI.

**Comment by clalancette** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18579/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13123/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19318/)

**Comment by clalancette** [comment]
OK, this one looks good to me.  @fujitatomoya can you take another look, and if you agree approve and merge this one?  Thanks.

**Review by fujitatomoya — APPROVED** [review]

**Comment by fujitatomoya** [comment]
@clalancette thanks!
