### PR TITLE
Relieve timer test period not to miss the cycle.

### LINKED ISSUE #1208: Flaky `test_timer` on Windows
## Description

The flakiness was caught when testing rmw_zenoh. We found that this test sometimes fails even with other RMWs.

The following two tests are flaky.
- TestPreInitTimer.test_timer_info
- TestPreInitTimer.test_timer_info_detect_overrun

## Logs
- Success
```console
❯ C:/dev/ws/build/rcl/test/Release/test_timer.exe --gtest_filter=TestPreInitTimer.test
_timer_info
Running main() from C:\dev\ws-rolling\install\src\gtest_vendor\src\gtest_main.cc
Note: Google Test filter = TestPreInitTimer.test_timer_info
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from TestPreInitTimer
[ RUN      ] TestPreInitTimer.test_timer_info
2025-02-11T07:44:49.624122Z  INFO ThreadId(02) zenoh::net::runtime: Using ZID: 6e804fe
23ec1a7727940cbcd425202cb
2025-02-11T07:44:49.628117Z  INFO ThreadId(02) zenoh::net::runtime::orchestrator: Zeno
h can be reached at: tcp/[::1]:50282
2025-02-11T07:44:49.682638Z  INFO ThreadId(02) zenoh::api::session: close session zid=
6e804fe23ec1a7727940cbcd425202cb
[       OK ] TestPreInitTimer.test_timer_info (63 ms)
[----------] 1 test from TestPreInitTimer (63 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (65 ms total)
[  PASSED  ] 1 test.
```

- Failure: The timestamp difference is about 10ms if the test fails.
```console
❯ C:/dev/ws/build/rcl/test/Release/test_timer.exe --gtest_filter=TestPreInitTimer.test
_timer_info
Running main() from C:\dev\ws-rolling\install\src\gtest_vendor\src\gtest_main.cc
Note: Google Test filter = TestPreInitTimer.test_timer_info
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from TestPreInitTimer
[ RUN      ] TestPreInitTimer.test_timer_info
2025-02-11T07:44:50.322553Z  INFO ThreadId(02) zenoh::net::runtime: Using ZID: bebfee2
cd86cdfed360c3a64beee2cd5
2025-02-11T07:44:50.327007Z  INFO ThreadId(02) zenoh::net::runtime::orchestrator: Zeno
h can be reached at: tcp/[::1]:50284
C:\dev\ws\src\rcl\rcl\test\rcl\test_timer.cpp(1021): error: Expected equality of these
values:
next_expected_call_time
  Which is: 1739259890367916900
call_info.expected_call_time
  Which is: 1739259890377916900

2025-02-11T07:44:50.387349Z  INFO ThreadId(02) zenoh::api::session: close session zid=
bebfee2cd86cdfed360c3a64beee2cd5
[  FAILED  ] TestPreInitTimer.test_timer_info (69 ms)
[----------] 1 test from TestPreInitTimer (70 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (70 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] TestPreInitTimer.test_timer_info
```

## Setup

- Windows 10 VM with [ROS2 rolling installed](https://github.com/ros2/ros2_documentation/pull/4989).
- RCL: https://github.com/ros2/rcl/commit/1427bbb73af6bda69036e5efe1255dfb90329186

### PR DESCRIPTION
**Pull request by fujitatomoya**
closes https://github.com/ros2/rcl/issues/1208

> [!NOTE]
> backport required to jazzy.

### CODE REVIEW

File: rcl/test/rcl/test_timer.cpp [hunk 1]
```diff
@@ -995,7 +995,7 @@ TEST_F(TestPreInitTimer, test_timer_info) {
   rcl_timer_call_info_t call_info;
   call_info.actual_call_time = 0;
   call_info.expected_call_time = 0;
-  int64_t period = RCL_MS_TO_NS(10);
+  int64_t period = RCL_MS_TO_NS(100);
```
Comment (fujitatomoya) [inline rcl/test/rcl/test_timer.cpp:998]: on 1st `rcl_timer_call_with_info`, it already misses the cycle, that eventually leads to the mismatch in line 1021.

**Review by fujitatomoya — COMMENTED** [review]
@jmachowinski what do you think? if you have better idea, i am listening!

**Comment by fujitatomoya** [comment]
Pulls: ros2/rcl#1209
Gist: https://gist.githubusercontent.com/fujitatomoya/16d41f9dce4cbc5abcd53f247d64cf09/raw/b72ffdca3977184d6482fca283498e06c8379f5d/ros2.repos
BUILD args:  --packages-up-to rcl
TEST args:  --packages-select rcl
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/15187
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/22524/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16772/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/2046/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/23317/)

**Review by ahcorde — APPROVED** [review]

**Comment by ahcorde** [comment]
https://github.com/Mergifyio backport jazzy

File: rcl/test/rcl/test_timer.cpp (hunk 1 above)
Comment (jmachowinski) [reply rcl/test/rcl/test_timer.cpp:998]: We could use mimick to mock rcl_clock_get_now.
