### PR TITLE
Fix that not to deallocate event impl in some failure case

### LINKED ISSUE #789: rcl_[publisher/subscription]_event_init not to deallocate event->impl if not return successfully
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - source
- Version or commit hash:
  - e88b63ba3c153dec6f1e5f0cc76137a728d68e42
- DDS implementation:
  - cyclonedds or fastrtps
- Client library (if applicable):
  - rcl

#### Steps to reproduce issue

```
$ colcon build --cmake-args -DCMAKE_BUILD_TYPE=Debug --packages-up-to rcl
$ . install/setup.bash
$ valgrind --leak-check=full ./build/rcl/test/test_events__rmw_cyclonedds_cpp  // or test_events__rmw_fastrtps_cpp
```

#### Expected behavior
No memory leak

#### Actual behavior
<details><summary> memory leak via valgrind </summary>
<p>

```shell
==255287== 64 bytes in 1 blocks are definitely lost in loss record 4 of 19
==255287==    at 0x483D7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==255287==    by 0x50AFF06: __default_allocate (allocator.c:37)
==255287==    by 0x48626D4: rcl_publisher_event_init (event.c:59)
==255287==    by 0x19AAB1: TestEventFixture_test_bad_event_ini_Test::TestBody() (test_events.cpp:712)
==255287==    by 0x1E1B29: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2447)
==255287==    by 0x1DA768: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2483)
==255287==    by 0x1B638B: testing::Test::Run() (gtest.cc:2522)
==255287==    by 0x1B6D84: testing::TestInfo::Run() (gtest.cc:2703)
==255287==    by 0x1B7475: testing::TestCase::Run() (gtest.cc:2825)
==255287==    by 0x1C2B5E: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5216)
==255287==    by 0x1E3023: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2447)
==255287==    by 0x1DB87C: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2483)
==255287== 
==255287== 64 bytes in 1 blocks are definitely lost in loss record 5 of 19
==255287==    at 0x483D7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==255287==    by 0x50AFF06: __default_allocate (allocator.c:37)
==255287==    by 0x48628E3: rcl_subscription_event_init (event.c:102)
==255287==    by 0x19AB92: TestEventFixture_test_bad_event_ini_Test::TestBody() (test_events.cpp:719)
==255287==    by 0x1E1B29: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2447)
==255287==    by 0x1DA768: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2483)
==255287==    by 0x1B638B: testing::Test::Run() (gtest.cc:2522)
==255287==    by 0x1B6D84: testing::TestInfo::Run() (gtest.cc:2703)
==255287==    by 0x1B7475: testing::TestCase::Run() (gtest.cc:2825)
==255287==    by 0x1C2B5E: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5216)
==255287==    by 0x1E3023: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2447)
==255287==    by 0x1DB87C: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2483)

```

</p>
</details>

### PR DESCRIPTION
**Pull request by iuhilnehc-ynos**
Fixes #789

Signed-off-by: Chen Lihui <Lihui.Chen@sony.com>

### CODE REVIEW

File: rcl/src/rcl/event.c [hunk 1]
```diff
@@ -79,10 +69,29 @@ rcl_publisher_event_init(
...
     rmw_event_type);
+  if (ret != RMW_RET_OK) {
+    goto fail;
+  }
+
+  return RCL_RET_OK;
+fail:
+  allocator->deallocate(event->impl, allocator->state);
+  event->impl = NULL;
+  return ret;
```
Comment (fujitatomoya) [inline rcl/src/rcl/event.c:94]: do we need to introduce `goto` statement here? instead of that i would do the following.

1. check error if not `RMW_RET_OK`.
2. if error happens, call deallocation.
3. then convert return code from `rmw` to `rcl`.
4. return it.

what do you think?

File: rcl/src/rcl/event.c [hunk 2]
```diff
@@ -125,10 +124,29 @@ rcl_subscription_event_init(
...
```
Comment (fujitatomoya) [inline rcl/src/rcl/event.c:149]: same here.

File: rcl/src/rcl/event.c (hunk 1 above)
Comment (iuhilnehc-ynos) [reply rcl/src/rcl/event.c:94]: I thought that before. I choose this one because I was thinking it will be less modification if there will be some extra logic in the future.

Comment (fujitatomoya) [reply rcl/src/rcl/event.c:94]: okay understood.

Comment (clalancette) [inline rcl/src/rcl/event.c:94]:
```suggestion
  return rcl_convert_rmw_ret_to_rcl_ret(ret);
```

File: rcl/src/rcl/event.c [hunk 3]
```diff
@@ -125,10 +124,29 @@ rcl_subscription_event_init(
       RCL_SET_ERROR_MSG("Event type for subscription not supported");
       return RCL_RET_INVALID_ARGUMENT;
   }
-  return rmw_subscription_event_init(
+
```
Comment (clalancette) [inline rcl/src/rcl/event.c:127]: All of the same comments from above apply here as well.

**Review by clalancette — CHANGES_REQUESTED** [review]

File: rcl/src/rcl/event.c (hunk 1 above)
Comment (iuhilnehc-ynos) [reply rcl/src/rcl/event.c:94]: @clalancette 

Thank you. I'll update it.

**Comment by iuhilnehc-ynos** [comment]
@ros-pull-request-builder retest this please

**Review by clalancette — APPROVED** [review]
Looks good to me, thanks for iterating.  I'll run CI on this next.

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12228/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7211/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9953/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12127/)
