### PR TITLE
Fix memory leak because of mock test

### LINKED ISSUE #799: Memory leak because of mock test
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - source
- Version or commit hash:
  - f3396a2a7dcf061d92642a8dd2af0b1673d36057
- DDS implementation:
  - fastrtps
- Client library (if applicable):
  - rcl

#### Steps to reproduce issue

```
$ colcon build --cmake-args -DCMAKE_BUILD_TYPE=Debug --packages-up-to rcl
$ . install/setup.bash
$ valgrind --leak-check=full ./build/rcl/test/test_init__rmw_fastrtps_cpp
```

#### Expected behavior
No memory leak

#### Actual behavior
<details><summary> memory leak via valgrind </summary>
<p>

```shell
==2206875== HEAP SUMMARY:
==2206875==     in use at exit: 664 bytes in 8 blocks
==2206875==   total heap usage: 2,560 allocs, 2,552 frees, 1,171,314 bytes allocated
==2206875== 
==2206875== 144 bytes in 1 blocks are definitely lost in loss record 6 of 8
==2206875==    at 0x483F7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==2206875==    by 0x49A4F46: __default_allocate (allocator.c:37)
==2206875==    by 0x4867C98: rcl_init_options_init (init_options.c:51)
==2206875==    by 0x12FD4D: TestRCLFixture__rmw_fastrtps_cpp_test_mocked_rcl_init_options_fini_Test::TestBody() (test_init.cpp:542)
==2206875==    by 0x1755B9: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2447)
==2206875==    by 0x16DED2: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2483)
==2206875==    by 0x149B21: testing::Test::Run() (gtest.cc:2522)
==2206875==    by 0x14A51A: testing::TestInfo::Run() (gtest.cc:2703)
==2206875==    by 0x14AC0B: testing::TestCase::Run() (gtest.cc:2825)
==2206875==    by 0x1562F4: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5216)
==2206875==    by 0x176AB3: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2447)
==2206875==    by 0x16EFE6: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2483)
==2206875== 
==2206875== 144 bytes in 1 blocks are definitely lost in loss record 7 of 8
==2206875==    at 0x483F7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==2206875==    by 0x49A4F46: __default_allocate (allocator.c:37)
==2206875==    by 0x4867C98: rcl_init_options_init (init_options.c:51)
==2206875==    by 0x48680A4: rcl_init_options_copy (init_options.c:84)
==2206875==    by 0x1307B9: TestRCLFixture__rmw_fastrtps_cpp_test_rcl_init_copy_mocked_fail_fini_Test::TestBody() (test_init.cpp:560)
==2206875==    by 0x1755B9: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2447)
==2206875==    by 0x16DED2: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2483)
==2206875==    by 0x149B21: testing::Test::Run() (gtest.cc:2522)
==2206875==    by 0x14A51A: testing::TestInfo::Run() (gtest.cc:2703)
==2206875==    by 0x14AC0B: testing::TestCase::Run() (gtest.cc:2825)
==2206875==    by 0x1562F4: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5216)
==2206875==    by 0x176AB3: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2447)
==2206875== 
==2206875== 144 bytes in 1 blocks are definitely lost in loss record 8 of 8
==2206875==    at 0x483F7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==2206875==    by 0x49A4F46: __default_allocate (allocator.c:37)
==2206875==    by 0x4867C98: rcl_init_options_init (init_options.c:51)
==2206875==    by 0x48680A4: rcl_init_options_copy (init_options.c:84)
==2206875==    by 0x13114E: TestRCLFixture__rmw_fastrtps_cpp_test_rcl_init_options_copy_fail_rmw_copy_Test::TestBody() (test_init.cpp:585)
==2206875==    by 0x1755B9: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2447)
==2206875==    by 0x16DED2: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2483)
==2206875==    by 0x149B21: testing::Test::Run() (gtest.cc:2522)
==2206875==    by 0x14A51A: testing::TestInfo::Run() (gtest.cc:2703)
==2206875==    by 0x14AC0B: testing::TestCase::Run() (gtest.cc:2825)
==2206875==    by 0x1562F4: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5216)
==2206875==    by 0x176AB3: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2447)
==2206875== 
==2206875== LEAK SUMMARY:
==2206875==    definitely lost: 432 bytes in 3 blocks
==2206875==    indirectly lost: 0 bytes in 0 blocks
==2206875==      possibly lost: 0 bytes in 0 blocks
==2206875==    still reachable: 232 bytes in 5 blocks
==2206875==         suppressed: 0 bytes in 0 blocks
==2206875== Reachable blocks (those to which a pointer was found) are not shown.
==2206875== To see them, rerun with: --leak-check=full --show-leak-kinds=all

```

</p>
</details>

### PR DESCRIPTION
**Pull request by iuhilnehc-ynos**
Fixes #799 

Signed-off-by: Chen Lihui <Lihui.Chen@sony.com>

### CODE REVIEW

File: rcl/test/rcl/test_init.cpp [hunk 1]
```diff
@@ -544,6 +544,10 @@ TEST_F(CLASSNAME(TestRCLFixture, RMW_IMPLEMENTATION), test_mocked_rcl_init_optio
   auto mock = mocking_utils::inject_on_return("lib:rcl", rmw_init_options_fini, RMW_RET_ERROR);
   EXPECT_EQ(RCL_RET_ERROR, rcl_init_options_fini(&init_options));
   rcl_reset_error();
+  {
+    auto mock = mocking_utils::inject_on_return("lib:rcl", rmw_init_options_fini, RCL_RET_OK);
```
Comment (clalancette) [inline rcl/test/rcl/test_init.cpp:548]:
```suggestion
    auto mock = mocking_utils::inject_on_return("lib:rcl", rmw_init_options_fini, RMW_RET_OK);
```

Also, why the additional scope?  Same goes for the ones below.

Comment (iuhilnehc-ynos) [reply rcl/test/rcl/test_init.cpp:548]: Because I didn't want to add a name with `mock1` before.
If using 
`mock = mocking_utils::inject_on_return("lib:rcl", rmw_init_options_fini, RMW_RET_OK);`
, failed as
```
/home/sharedata/Linux/ROS2/docker_ros2_master/src/ros2/rcl/rcl/test/rcl/../mocking_utils/patch.hpp:460:55: error: no match for ‘operator=’ (operand types are ‘mocking_utils::Patch<7, int(rmw_init_options_t*)>’ and ‘mocking_utils::Patch<8, int(rmw_init_options_t*)>’)
```

OK, I'll not use the additional scope.

**Review by fujitatomoya — APPROVED** [review]
lgtm, i think that is enough to call deallocator.

**Review by clalancette — APPROVED** [review]

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12312/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7281/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10025/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12207/)
